import io
from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH


def set_heading(doc, text, level=1):
    heading = doc.add_heading(text, level=level)
    run = heading.runs[0]
    run.font.color.rgb = RGBColor(0x4F, 0x46, 0xE5)  # indigo
    return heading


def set_body(doc, text):
    para = doc.add_paragraph(text)
    para.runs[0].font.size = Pt(11)
    return para


def add_divider(doc):
    doc.add_paragraph("─" * 60)


def build_prd_docx(
    original_feedback: str,
    jtbd_output: str,
    persona_output: str,
    pain_point_output: str,
    opportunity_output: str,
    prd_output: str
) -> bytes:
    """
    Takes all agent outputs.
    Returns a .docx file as bytes — ready for Streamlit download button.
    """

    doc = Document()

    # ── Page margins ───────────────────────────────
    for section in doc.sections:
        section.top_margin    = Inches(1)
        section.bottom_margin = Inches(1)
        section.left_margin   = Inches(1.2)
        section.right_margin  = Inches(1.2)

    # ── Cover ──────────────────────────────────────
    title = doc.add_heading("AI Product Manager Report", 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title.runs[0].font.color.rgb = RGBColor(0x4F, 0x46, 0xE5)

    subtitle = doc.add_paragraph("Generated by AI PM Agent Pipeline")
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    subtitle.runs[0].font.color.rgb = RGBColor(0x6B, 0x72, 0x80)
    subtitle.runs[0].font.size = Pt(11)

    doc.add_paragraph()
    add_divider(doc)
    doc.add_paragraph()

    # ── Original feedback ──────────────────────────
    set_heading(doc, "Original User Feedback", level=1)
    set_body(doc, original_feedback.strip())
    doc.add_paragraph()

    # ── Agent outputs ──────────────────────────────
    sections = [
        ("Agent 1 — JTBD Analysis",       jtbd_output),
        ("Agent 2 — User Persona",         persona_output),
        ("Agent 3 — Pain Point Analysis",  pain_point_output),
        ("Agent 4 — Opportunity Scoring",  opportunity_output),
        ("Agent 5 — Product Requirements Document", prd_output),
    ]

    for section_title, content in sections:
        doc.add_page_break()
        set_heading(doc, section_title, level=1)
        add_divider(doc)
        doc.add_paragraph()

        # Split content into paragraphs and add each one
        for line in content.strip().split("\n"):
            line = line.strip()
            if not line:
                doc.add_paragraph()
                continue

            # Lines that look like headers get styled differently
            if line.startswith("──") or line.startswith("══"):
                p = doc.add_paragraph(line)
                p.runs[0].font.color.rgb = RGBColor(0x6B, 0x72, 0x80)
                p.runs[0].font.size = Pt(9)

            elif line.startswith("#") or line.isupper():
                sub = doc.add_heading(line, level=2)
                sub.runs[0].font.size = Pt(12)
                sub.runs[0].font.color.rgb = RGBColor(0x1F, 0x29, 0x37)

            elif line.startswith("-") or line.startswith("•"):
                p = doc.add_paragraph(line, style="List Bullet")
                p.runs[0].font.size = Pt(11)

            else:
                set_body(doc, line)

    # ── Save to bytes buffer ───────────────────────
    # We return bytes instead of saving to disk
    # so Streamlit can offer it as a download
    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer.getvalue()